# Build settings
# Gems
gems:
- jekyll-paginate
- jekyll-feed

# url is the full website URL
# baseurl is the website's URL without the hostname
# If you are hosting it on Github for some project with name 'projectname', then the url and baseurl should look like:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"
url: "https://andrew659.github.io"
enforce_ssl: ""
baseurl: ""

# Title of website
title: Yepang Liu's Research Blog

#Default keywords (used if no keywords are specified on a page basis)
keywords: software engineering, testing, software analysis, Android

# Short description of your site
desc: Yepang Liu's Research Blog

# --- Navigation bar options --- #

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/avatar.jpg"

# List of links in the navigation bar
nav-links:
#  Home: ""
  About Me: "aboutme"
  Posts by Category: "categories"
  Archive: "archive"
#  Say Hello: "contact"

# --- Footer options --- #

# If the values are empty, they are ignored
profile:
  name: Yepang Liu (Andrew)
  email: andrew659@gmail.com
  facebook: andrew659
  github: andrew659
  twitter: andrew659
  linkedin: andrew659@gmail.com
#  stackoverflow: your-stackoverflow-id

# To display link in the footer section
pretty-url: "Yepang Liu"

# --- Misc --- #

# Your Disqus profile (shortname) settings
disqus: "https-andrew659-github-io"

# Google Analytics Settings
google_analytics: "UA-88403869-1"

# Set these options as you need (For more information, check Jekyll's site)
timezone: "Hongkong"
markdown: kramdown
#highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /blog/:title
paginate: 5

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "default"
      show-avatar: true

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

created-by: Babji, Chetty
creator-url: https://bchetty.com

#ensure we can run custom plugins
safe: false

#allow future post date
future: ture

show_drafts: false
